// <auto-generated />
using IAB251InterportCargoAssignment2Grp21.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IAB251InterportCargoAssignment2Grp21.Migrations
{
    [DbContext(typeof(InterportCargoContext))]
    [Migration("20260529111738_UpdateEmployeeCredentialHash")]
    partial class UpdateEmployeeCredentialHash
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.16");

            modelBuilder.Entity("IAB251InterportCargoAssignment2Grp21.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("FamilyName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers", (string)null);
                });

            modelBuilder.Entity("IAB251InterportCargoAssignment2Grp21.Models.LocalEmployeeCredential", b =>
                {
                    b.Property<int>("LocalEmployeeCredentialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("EmployeeKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("LocalEmployeeCredentialId");

                    b.ToTable("Employee", (string)null);

                    b.HasData(
                        new
                        {
                            LocalEmployeeCredentialId = 1,
                            Email = "t.williams@company.com",
                            EmployeeKey = "$2a$11$HiTNiU8zE0EKIsFF0VcJheN74BbrxHVgDT9EjU8/ZhtdeLbR9LFNK"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
