// <auto-generated />
using System;
using IAB251InterportCargoAssignment2Grp21.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IAB251InterportCargoAssignment2Grp21.Migrations
{
    [DbContext(typeof(InterportCargoContext))]
    [Migration("20260527123936_FixSchema")]
    partial class FixSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.16");

            modelBuilder.Entity("IAB251InterportCargoAssignment2Grp21.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("FamilyName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers", (string)null);
                });

            modelBuilder.Entity("IAB251InterportCargoAssignment2Grp21.Models.LocalEmployeeCredential", b =>
                {
                    b.Property<int>("LocalEmployeeCredentialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("EmployeeKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("LocalEmployeeCredentialId");

                    b.ToTable("Employee", (string)null);

                    b.HasData(
                        new
                        {
                            LocalEmployeeCredentialId = 1,
                            Email = "t.williams@company.com",
                            EmployeeKey = "QUOTE123"
                        });
                });

            modelBuilder.Entity("IAB251InterportCargoAssignment2Grp21.Models.Quotation", b =>
                {
                    b.Property<int>("QuotationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AdditionalCharges")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("BaseRate")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("ContainerType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateIssued")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DepotCharges")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("DiscountApplied")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DiscountReason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LclDeliveryCharges")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("OfficerEmail")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("QuotationNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("RequestId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("QuotationId");

                    b.HasIndex("RequestId")
                        .IsUnique();

                    b.ToTable("Quotations", (string)null);
                });

            modelBuilder.Entity("IAB251InterportCargoAssignment2Grp21.Models.QuotationMessage", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RequestId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SentBy")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("MessageId");

                    b.HasIndex("RequestId");

                    b.ToTable("QuotationMessages", (string)null);
                });

            modelBuilder.Entity("IAB251InterportCargoAssignment2Grp21.Models.QuotationRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdditionalNotes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsExport")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsImport")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberOfContainers")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PackageNature")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("RequiresPacking")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RequiresQuarantine")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RequiresUnpacking")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("RequestId");

                    b.HasIndex("CustomerId");

                    b.ToTable("QuotationRequests", (string)null);
                });

            modelBuilder.Entity("IAB251InterportCargoAssignment2Grp21.Models.Quotation", b =>
                {
                    b.HasOne("IAB251InterportCargoAssignment2Grp21.Models.QuotationRequest", "QuotationRequest")
                        .WithOne("Quotation")
                        .HasForeignKey("IAB251InterportCargoAssignment2Grp21.Models.Quotation", "RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuotationRequest");
                });

            modelBuilder.Entity("IAB251InterportCargoAssignment2Grp21.Models.QuotationMessage", b =>
                {
                    b.HasOne("IAB251InterportCargoAssignment2Grp21.Models.QuotationRequest", "QuotationRequest")
                        .WithMany("Messages")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuotationRequest");
                });

            modelBuilder.Entity("IAB251InterportCargoAssignment2Grp21.Models.QuotationRequest", b =>
                {
                    b.HasOne("IAB251InterportCargoAssignment2Grp21.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("IAB251InterportCargoAssignment2Grp21.Models.QuotationRequest", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("Quotation");
                });
#pragma warning restore 612, 618
        }
    }
}
